name: webhook test

on:
    workflow_dispatch:
  
    # Allows external webhook trigger
    repository_dispatch:
      types:
        - webhook

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: test
              run: echo "test"
