name: webhook test

on:
    workflow_dispatch:
  
    # Allows external webhook trigger
    repository_dispatch:
      types:
        - member

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@main
            - name: Print Webhook Payload
              run: |
                echo "${{ toJson(github.event.client_payload) }}"
                echo "${{ github.event.client_payload }}"
            - name: run script
              run: |
                python3 test.py '${{ toJson(github.event.client_payload) }}'

            - name: export output
              id: run_script
              run: |
                # echo "changes = $(python3 test.py '${{ toJson(github.event.client_payload) }}')" >> "$GITHUB_OUTPUT"
                echo "changes = $(python3 test.py $(echo '${{ toJson(github.event.client_payload) }}' | jq -c -R .))" >> "$GITHUB_OUTPUT"
            - name: print output
              run: |
                echo ${{ steps.run_script.outputs.changes }}
