name: webhook test

on:
    workflow_dispatch:
  
    # Allows external webhook trigger
    repository_dispatch:
      types:
        - member

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@main
            - name: Print Webhook Payload
              run: |
                echo "${{ toJson(github.event.client_payload) }}"
                echo "${{ github.event.client_payload }}"
            - name: run script
              run: |
                python3 test.py -d ${{ toJson(github.event.client_payload) }}
