name: webhook test

on:
    workflow_dispatch:
  
    # Allows external webhook trigger
    repository_dispatch:
      types:
        - member

jobs:
    test:
        permissions:
            contents: write
            pull-requests: write
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@main
            - name: Print Webhook Payload
              run: |
                echo "${{ toJson(github.event.client_payload) }}"
                echo "${{ github.event.client_payload }}"
            - name: export output
              id: run_script
              env:
                PAYLOAD: ${{ toJson(github.event.client_payload) }}
              run: |
                changes=$(python3 test.py "$PAYLOAD")
                echo $changes
                echo "changes=$changes" >> "$GITHUB_OUTPUT"
            - name: print output
              run: |
                echo ${{ steps.run_script.outputs.changes }}
            - name: Open PR
              id: open_pr
              if : steps.run_script.outputs.changes != 'None'
              run: |
                git config --global user.email "github-actions[bot]@users.noreply.github.com"
                git config --global user.name "github-actions[bot]"
                git switch -c 'changes_to_${{github.event.client_payload.repo}}_repo' -m
                git add * && git commit -m "includes changes to ${{github.event.client_payload.repo}} repo"
                git push -u origin 'changes_to_${{github.event.client_payload.repo}}_repo'
                gh pr create -B main \
                  --title 'Changes to ${{github.event.client_payload.repo}} repo' \
                  --body ${{ steps.run_script.outputs.changes }}
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
